# Generated by Django 5.2.5 on 2026-06-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=999999999, help_text='User AI usage credits'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='currency',
            field=models.CharField(choices=[('PHP', 'Philippine Peso'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='PHP', max_length=5),
        ),
    ]
